version: "3.9"

services:
  psql:
    container_name: db
    image: postgres:14.1-alpine
    volumes:
        - ./backup_data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  backend:
    #image: jihxdul/everypenny-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - psql
  
  frontend:
    #image: jihxdul/everypenny-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - 80:80
  
  nginx_backend_server:
    #image: jihxdul/everypenny-nginx
    build: ./nginx_backend_server
    ports:
        - 8000:8000
    depends_on:
        - backend
