version: "3"

services:
  database:
    image: postgres:12.7-alpine
    volumes:
        - ./backup_data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  backend:
    # image: as4259/everypenny-backend
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - database
  
  frontend:
    # image: as4259/everypenny-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - 80:80
  
  nginx_backend_server:
    # image: as4259/everypenny-nginx
    build: ./nginx_backend_server
    ports:
        - 8000:8000
    depends_on:
        - backend
